[workspace]
members = [
  "attestation-doc-validation",
  "python-attestation-bindings",
  "node-attestation-bindings",
  "swift-attestation-bindings",
  "wasm-attestation-bindings"
]

[profile.release]
lto = true
