on:
  push:
    paths:
      - attestation-doc-validation/**
      - node-attestation-bindings/**
      - .github/workflows/lint-and-test.yml
name: Lint and Test
jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cargo install cargo-make
      - run: cargo make ci
